### ISSUE TITLE
Multiplatoform plans? 

### ISSUE THREAD

**Issue by ANDREW007CZ** [jenspfahl/ANOTHERpass#11]
Hi, very much like your software. Are there any plans on having it multiplatform e. g.  for Windows? Like Keepass is, but I prefer your software over it.

Sorry for posting a question in issues.

**Comment by jenspfahl** [comment]
Hi! Thanks for appreciating my project. At the moment i am focusing on Android, nothing else. It is also a question of time. And, tbh i am not a Windows user ;-) . But the source code is MIT, maybe someone else would like to work on that.
