### ISSUE TITLE
Feature request : Add support for kdbx (KeePass database).

### ISSUE THREAD

**Issue by 4mohamedaliii** [jenspfahl/ANOTHERpass#16]
Why you don't add support for kdbx (KeePass database)?
So it will be easy to use database on other paltforms right now it's difficult to import or export passwords on other paltforms.

**Comment by jenspfahl** [comment]
I was also thinking about doing this. But it is not trivial to implement so it will take some time to do it. Thanks for your proposal!

**Comment by kadircanersahin** [comment]
Ani way import from BitWarden?
