### ISSUE TITLE
Heads-up on quantum supremacy risks

### ISSUE THREAD

**Issue by leo-lb** [jenspfahl/ANOTHERpass#25]
Hello,

On your [website](https://anotherpass.jepfa.de/why/)  you write:

"Many password managers use the cloud to sync between platforms. So you have to trust that NSA doesn’t read your encrypted passwords from the cloud and tries to crack your master password with a quantum computer."

Most common implementations of master passwords are symnetric encryption such as AES, AES and others symnetric encryption algorithms are not threatened by quantum supremacy. Only asymnetric encryption algorithms are at risk, such as RSA or ECDSA.

https://crypto.stackexchange.com/questions/25389/are-there-any-quantum-resistant-symmetric-encryption-schemes

Namely, AES-256 is quantum-safe.

Regards

**Comment by jenspfahl** [comment]
Thanks for your remarks.
You are right, i have updated this sentence.
