### ISSUE TITLE
Desktop application

### ISSUE THREAD

**Issue by Lucas-Sichardt** [jenspfahl/ANOTHERpass#26]
Hello and thank you for this very interesting application.

Is there a plan for a desktop application for Linux?
I think this would be very nice especially to have a backup whem your smartphone geys lost or broken suddenly...

Best regards,

Lucas

**Comment by jenspfahl** [comment]
Hi! 
It is not planned to port it to Linux. I would also appreciate that and I see the need to have a Linux version but I don't have any deeper experience in Linux UI or CLI development.
Further the app shall remain an offline app where users are self responsible to backup their data. To have different clients would also require to sync data between by hand.

Best regards

**Comment by Lucas-Sichardt** [comment]
Hi!

I understand the problem. Would be nice if someone would be intetested in building the ui for a desktop version.
I appreciate the offline application policy.
In fact iI would sync by exporting the vault manually - if wanted, one could also use Nextcloud or something perhaps.
But the main problem is the effort of building the desktop ui or finding someone for this.
If I had a bit spare time I would do it but unfortunately it's not the case. And my experience in this is also limited...

Best regards,

Lucas
-- 
Lucas Sichardt
***@***.***
http://lucas.sichardt.net

(Diese E-Mail habe ich von einem Mobiltelefon aus geschickt; eine eventuell erhöhte Häufigkeit von dadurch bedingten Tippfehlern bitte ich zu entschuldigen.)

Am 10. Oktober 2022 21:47:43 MESZ schrieb Jens Pfahl ***@***.***>:
