### ISSUE TITLE
Issue importing credentials from csv file

### ISSUE THREAD

**Issue by alexgrassl** [jenspfahl/ANOTHERpass#29]
Thanks for this awesome app, appreciate it a lot.

I have encountered a problem while trying to import my csv file from firefox. After pressing the load button, the app tells me it does not have the necessary permissions.

I´m running the latest GrapheneOS Build, the only permissions I can grant are for sensors and camera.
Maybe this is an OS problem, I tried restarting several times.

Best regards.

**Comment by jenspfahl** [comment]
This is weird, i haven't encountered any problems like that. But i don't use Graphene and i guess most users don't use it neither. I know Graphene is very strict in giving permissions by default, but there must be an option to manage permissions for apps in Graphene. There you might grant the permission to allow the app accessing your storage.

**Comment by alexgrassl** [comment]
It also says I don´t have enough permission to export my vault.
Seems to have something to do with the OS, but I couldn´t figure out what´s the problem so far. 

But you are right, Graphene won´t be one of the favourite OSes.
So maybe just keep it in mind.

**Comment by jenspfahl** [comment]
Hey, this problem should be resolved with the next version of the app (1.7.2). It will be delivered through F-Droid the next days.
