### ISSUE TITLE
[FEATURE REQUEST] Copy password

### ISSUE THREAD

**Issue by 0xlne** [jenspfahl/ANOTHERpass#32]
Once a password has been generated or retrieved, as a user, I want to have the possibility of copying it to paste in the required login form.
If I am logging into different services several times a day, typing 1 character at a time of that complex password generated by Anotherpass is time consuming & counterproductive.
At the very least enable a user toggle in the settings to allow/prevent passwords to be copied.

**Comment by jenspfahl** [comment]
There is still a setting to enable it under Settings/Clipboard settings/Enable copying password .
If enabled you will see a copy icon on top in the actions bar.

**Comment by 0xlne** [comment]
Thank you for pointing this out; I missed it.
