### ISSUE TITLE
Can't import vault, A13

### ISSUE THREAD

**Issue by ANDREW007CZ** [jenspfahl/ANOTHERpass#33]
Hi, I'm using
Android 13
Sony Xperia 5 III

ANOTHERpass 1.7.1.

With update from Android 12 to version 13, I did a factory reset. I exported my vault and master key before the reset.

Now when try to LOAD VAULT FILE I get message "Permision denied!". There is no popping dialog to allow access to storage and, also there is no such option in settings (device's Settings>Applications>ANOTHERpass).
Permission for notification (new on A13) is greyed out and not possible to allow. I think it is somehow related.
I tried reinstalling and restarting device. Nothing seems to help.

**Comment by jenspfahl** [comment]
Hey, and sorry to have trouble with the app. I am also running on A13 but never encountered that.
Short question: do you see the app under Settings > Privacy > Permission manager > Files and media and can it be enabled there?

**Comment by jenspfahl** [comment]
Hi again, i found the bug in the app. It is not working anymore on A13 because the permissions to access the external storage are ignored by the system but the app still checks it. I gonna fix it soon.

**Comment by jenspfahl** [comment]
Ok, fix is on the way to F-Droid and Uptodown. F-Droid usually needs some days to gather and build it. If you need  the new version (v1.7.2) now you can download it directly from here https://anotherpass.jepfa.de/download/.

**Comment by ANDREW007CZ** [comment]
wow, man, thank you for that quick fix! You have better support than most paid services! :)))
