### ISSUE TITLE
Can seem to use autofill

### ISSUE THREAD

**Issue by YashaDimas** [jenspfahl/ANOTHERpass#36]
Hello good day,
I seem cannot use the autofill feature
And other feature works great like overlayz etc only autofill not working for me
Im using a Xiaomi phone and i enable autofill in setting to use AnotherPass instead of google

**Comment by jenspfahl** [comment]
Which Android version are you using?

**Comment by YashaDimas** [comment]
Im using android 11
After some extended research, it's not anotherpass problems.
Im using Brave Browser it seem to block 3rd party password manager i suppose
I could be wrong

**Comment by jenspfahl** [comment]
This could be. The app must support Autofill or at least not block it. 
One last try is to enable  "Autofill suggestion everywhere" in AnotherPass settings.

**Comment by amadoumx** [comment]
Same issue here: brave, chrome and even FOSS browser: no autofill, not prompting to save new login. Using OnePlus with Android 12. Autofill enabled.

**Comment by jenspfahl** [comment]
I can confirm that Autofill is kind of not supported by Chrome on my device as well, no matter which Autofill app i have configured. Until now i was not able to find out where to configure it. If somebody has an idea please let me know.

At least with the FOSS Browser Autofill works fine (tested with Android 13), but it has to be enabled in the FOSS Browser app settings.

**Comment by amadoumx** [comment]
I'm using android 12, there is no option to enable autofill in the foss browser.

**Comment by jenspfahl** [comment]
I use version 9.5 and there is a checkbox under Privacy / Form Data which needs to be enabled.
