### ISSUE TITLE
"Some optional info" field

### ISSUE THREAD

**Issue by ruafelianna** [jenspfahl/ANOTHERpass#39]
Hello!

Could you please make the "Some optional info" field a bit larger? For example, 300 characters instead of 200. 200 characters was barely enough to save all the recovery codes, and there was no enough space to save more information that I needed.

Also when I just view the credentials, if the "Some optional info" field is very long (more than 11 lines), I can only see those 11 lines. It would be wonderful if you could add some scrolling there.

Have a nice day! Cheers!

**Comment by jenspfahl** [comment]
The additional informations are still scrollable in the credential view, but you need to minimize the top bar first by sweeping it up. Maybe not the most intuitive solution but it should work at least as workaround. To improve that i could imagine an Expand-arrow in the view to collapse the information more easily.

**Comment by ruafelianna** [comment]
That worked, thank you :) But it indeed seems really counter-intuitive, so some other way of viewing that info would be very much appreciated. ❤️

**Comment by jenspfahl** [comment]
Expand arrow added with with v1.8.0
