### ISSUE TITLE
HELP PLEASE

### ISSUE THREAD

**Issue by Nic19774711** [jenspfahl/ANOTHERpass#42]
I have a problem and I no longer have access to the app. I know my pin but the fingerprint function has not worked several times. Now the app requires the exported master password, the QR code or NFC. I remember that I exported the master password but I can not find it but I urgently need help.

Device: Samsung Galaxy S21 Android 13

**Comment by jenspfahl** [comment]
Hi and sorry to hear that. 
The concept of the app (and also of almost all other serious password managers) is that a recovery without the main credentials (here pin and master password) is technically not possible. So the only way is unfortunately for you to find the exported master password. Maybe you have stored the QR as image file somewhere? It is usually a red QR code.

**Comment by Nic19774711** [comment]
Thank you i have only one QR Code in red but does it say that this is an access data password from Paypal?!

**Comment by jenspfahl** [comment]
I don't know. Is there an "EMP" (Exported Master Password) abbreviation on top of the QR code?

**Comment by Nic19774711** [comment]
Betonwerk--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 02.05.23, 09:46 schrieb Jens Pfahl ***@***.***>:

   
  I don't know. Is there an "EMP" (Exported Master Password) abbreviation on top of the QR code?
