### ISSUE TITLE
Monospace font for passwords

### ISSUE THREAD

**Issue by kzshantonu** [jenspfahl/ANOTHERpass#48]
Current font's capital I and lowercase L looks the same 
![Screenshot_2023-10-05-23-07-36-71_215601c78b9dbd26b7c23548c78185af](https://github.com/jenspfahl/ANOTHERpass/assets/7745374/a7b4541e-6b9b-47fa-90e7-acab990b3b6e)

**Comment by jenspfahl** [comment]
That's weird. Passwords are printed with monospace family fonts usually. Never seen an issue like yours. For some reason the app seems to cannot find a monospace font and falls back to a default. Which OS version and vendor do you use?

**Comment by kzshantonu** [comment]
OnePlus 7T Pro. Android 12

**Comment by jenspfahl** [comment]
A monospace font is now bundled with the app, so this should be fixed with the latest version.
