### ISSUE TITLE
Import vault file - format needed

### ISSUE THREAD

**Issue by linuxzsh** [jenspfahl/ANOTHERpass#50]
Hi. AnotherPass is great ! 
What about CSV format. please ? I don't find help/information nowhere.
What means "The vault file must belong to the same vault with the current vault ..." ?
Cant you give un short example ? e.g.
```
"Account","Login Name","Web Site","Password",
"Home wifi","","","ueco sevi qiev popi 5,"
```
Thanks

**Comment by jenspfahl** [comment]
You can import credentials from browsers like Firefox as csv file ("Import/Read" / "Import credentials from file"). You can also export all credentials out of the app as csv ("Export" / "Takeout credentials"). Both use a simple csv format that also matches when you export credentials from a browser. But be aware that the csv is totally unencrypted! Only use this to migrate credentials from a browser or out of the app. To backup your vault you should use the "Export vault" and "Import vault file" option instead.

**Comment by linuxzsh** [comment]
Okay.
Any idea to import CSV from KeepassDX ?
Message error : "Cannot read credentials from CSV file".
The only way is to re-write my csv file according the format of that produce Firefox ?

**Comment by linuxzsh** [comment]
This is one right CSV format :
```
"url","username","password","httpRealm","formActionOrigin","guid","timeCreated","timeLastUsed","timePasswordChanged"
"https://accounts.firefox.com","example@gmail.com","passwd",,"https://accounts.firefox.com","","","",""
```

**Comment by jenspfahl** [comment]
Yes this would be the workaround. 
I'll add the csv format of Keypass in the next version.

**Comment by jenspfahl** [comment]
The app now supports KeePass csv files to import from.
