### ISSUE TITLE
[Feature Request] Adaptive / Monochrome app icon support

### ISSUE THREAD

**Issue by sebastien46** [jenspfahl/ANOTHERpass#54]
Starting with [TargetSDK 33](https://developer.android.com/about/versions/13), devices can call the [getMonochrome()](https://developer.android.com/reference/android/graphics/drawable/AdaptiveIconDrawable#getMonochrome()) function from the [AdaptiveIconDrawable](https://developer.android.com/reference/android/graphics/drawable/AdaptiveIconDrawable) class, which can enable the app to render a user-themed / monochromatic version of it's [Drawable](https://developer.android.com/reference/kotlin/android/graphics/drawable/Drawable) icon:

![](https://developer.android.com/static/guide/practices/ui_guidelines/images/adaptive-icon-monochrome.png)

[Developer Reference Documentation](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive)

**Comment by sebastien46** [comment]
Here is a basic mockup I made for reference:
![icon](https://github.com/jenspfahl/ANOTHERpass/assets/57289288/cc00a6a0-cef8-455d-96c7-154397b93032)

**Comment by sebastien46** [comment]
@jenspfahl do you happen to have the original vector file used to make the bitmap ? (if there is one)

**Comment by jenspfahl** [comment]
Haven't had the time yet to look into this. But will consider this for the next release which will come for sure.

**Comment by sebastien46** [comment]
> Haven't had the time yet to look into this. But will consider this for the next release which will come for sure.

So, I've decided to take a closer look at this.

I've found an appropriate VectorDrawable in the repo: `app/src/main/res/drawable/ic_keywithqrcode_normal.xml`
I'm pretty sure it's the one you also used for the app icon, so I've recreated it using it.
Here's the comparison:

### Before

![scr1_color_old](https://github.com/jenspfahl/ANOTHERpass/assets/57289288/73e25c43-1ed6-46ef-ad2d-850f308a6f86)

### After

![scr1_color_new](https://github.com/jenspfahl/ANOTHERpass/assets/57289288/48725aae-1cda-4171-997f-296c796cc1a3)

The only things I'm mising are:
- The exact color hex you used for the background (I used the `colorAcent` value from `values/colors.xml`
- The full vector file with the shadow that's been used for creating the Bitmap icon

I also implemented the Themed / Monochrome icon as well:

### Dark Mode, Blue Swatch

![scr2_new_blue_dark](https://github.com/jenspfahl/ANOTHERpass/assets/57289288/75d1bdf7-6e57-496b-b43b-a0f71886bc9a)

### Light Mode, Yellow Swatch

![scr2_new_yellow_light](https://github.com/jenspfahl/ANOTHERpass/assets/57289288/8dc82b54-8640-4a91-97e9-0bb2161029fa)

**Comment by jenspfahl** [comment]
> The full vector file with the shadow that's been used for creating the Bitmap icon
I used an online icon generator which unfortunately only returned PNGs, no SVG or any other Vector files.

I have been looking into this and i am stuck in defining different adaptive-icon  layers for background, foreground and monochrome. Could you please share the vectors file for your created icons?

**Comment by jenspfahl** [comment]
I think I managed it. Stay tuned for release 1.9.0 !

**Comment by jenspfahl** [comment]
solved with v1.9.0
