### ISSUE TITLE
My NFC tag "write protected" when it's not?

### ISSUE THREAD

**Issue by languagemaniac** [jenspfahl/ANOTHERpass#55]
Hi, I just installed the app. Wanted to create a NFC token and just grabbed some mifare classic 1k (iso 14443-3A)  gen 2 CUID tags, but it says they're write protected.

I only used one of the 10 tags I bought some time ago to clone another NFC tag with "mifare classic tool" app and it worked, so I guess they're not write protected, so maybe the tag is not compatible? Or is it a bug?

In case it's because it's not supported, which types of tags are?

**Comment by jenspfahl** [comment]
The app currently supports the NDEF format  only. See here https://anotherpass.jepfa.de/faq/#3-what-is-a-nfc-tag-and-do-i-need-it
I have never tested with Mifare tags; do they support NDEF?

**Comment by languagemaniac** [comment]
> The app currently supports the NDEF format only. See here https://anotherpass.jepfa.de/faq/#3-what-is-a-nfc-tag-and-do-i-need-it I have never tested with Mifare tags; do they support NDEF?

I see, I missed that in the FAQ. Didn't know what NDEF was but it looks like my tags do not support it. I can close the issue now. Will try to get a ndef compatible tags such as the one suggested in the FAQ.

Closing the issue now
