### ISSUE TITLE
Multiple ndef records fail every time.

### ISSUE THREAD

**Issue by andmagdo** [jenspfahl/ANOTHERpass#70]
Hello,

I use an implant for nfc ndef reading. I note this not because it is potentially dysfunctional (it is an NTAG216), but that due to its nature as an implant, I only have one of it. Therefore, I try to be able to store multiple records on it, get more use out of one chip. I have 886 bytes that can be used and this app only uses less than 130 bytes

The issue comes up when I use the chip with AnotherPass. The ndef record works, but only when it is the only record on the chip. I have tried putting it in multiple positions (even the first one that I normally use for contacts) and no configuration with another record works.

I hope this is a relatively easy solve (but I don't write android apps, so I don't know)

**Comment by jenspfahl** [comment]
Hi!
I have been looking into this and i might have found the problem, but i have to test it first. Generally, writing data to a tag (by the app) will always overwrite the whole tag, but as far as i understand your comment, you can work around this. When it comes to reading, the app currently tries to append all records to one blob, assuming all data belongs to the app.  But there might be a way to filter out unrelated records. I'll let you know once i know more.

**Comment by andmagdo** [comment]
Thank you very much!

And yes, you can work around this. While the app does write the whole tag, tools like NFC tools and NXP tagwriter can add extra records (phones use the first record for autorun)
