### ISSUE TITLE
Unlocking vault from Autofill menu does show no entries in password list

### ISSUE THREAD

**Issue by ANDREW007CZ** [jenspfahl/ANOTHERpass#74]
bug repro:

1. tap on password input box
2. tap on unlock vault from context menu
3. app opens but no passwords are shown even with empty filter
4. when I go back to browser (firefox specificaly here) and tap on "select credential" (as vault's been already unlocked) the list of passwords is shown normally (without any need to re-type PIN or scan fingerprint)

anotherpass v 1.9.1
Android 13 (Sony Xperia 5 III)

Thank you!! :)

**Comment by jenspfahl** [comment]
I tried to reproduce but it works at last on my phone. But I discovered this behavior a few times before. I think it is a random problem, but will try to figure out how this could happen.

**Comment by jenspfahl** [comment]
Solved with v2.0.0.
