### ISSUE TITLE
Two Gamechanging Proposals :)

### ISSUE THREAD

**Issue by iuvi7** [jenspfahl/ANOTHERpass#75]
Hello!

Your password manager is cool! I would like to suggest two features wich would be super nice to implement 

1. Create Linux Windiws Mac version (finally with same functionality and design ;)

2. Airgapped password exchange by QR codes

For example: i sit in public space and need to transfer confidential info (password, text or so) to my or other's device, but it should be for sure encrypted in advance. So, there at first must be exchange of public key's (also by QR's) before start of "<-> back and forth" airgapped messaging 

- I generate secret and public key on Notebook and scan public key as QR code with my phone
- Now doing same with creating pair on phone and scan by webcam of my notebook PubKey of my Phone
- After connection get's - can send encrypted passwords\text by strong protected QR codes 

Could that be implemented in Anotherpass?

Thanks for your work :)

**Comment by jenspfahl** [comment]
Hi and thank you for your ideas. 

Regarding your first point I am actually working on a browser extension to make Anotherpass usable on other devices in the same local network. The idea is to link the phone app with the extension and be able to fetch credentials from the phone vault. Here comes public keys in play for secure encryption. But this is still under construction. 
Building native clients for each OS is very time consuming and therefore not in my agenda.

Regarding your second point there are already ways to share credentials between two Anotherpass apps. When it comes to sharing  across different platforms, the mentioned extension could be used. Over the air sharing without a network is a good idea but hard to implement.

**Comment by jenspfahl** [comment]
Point 1 is solved with v2.0.0 and the ANOTHERpass browser extension.
